Added setCornerRadius function to avoid `Ambiguous use of 'cornerRadius'` issue
whitesmith/WSTagsField pull request #148
Opened 2020-08-18 16:48 UTC by mobilestar1

2020-08-18 16:52 UTC, ricardopereira requested changes

2020-08-18 16:52 UTC, ricardopereira commented on Source/WSTagsField.swift
> +    /// Set corner radisu of tag views
Small typo in the comment.

2020-08-18 16:54 UTC, mobilestar1 commented on Source/WSTagsField.swift
> +    /// Set corner radisu of tag views
Sorry for typo. Thanks.

2020-08-18 17:08 UTC, mobilestar1 commented
@ricardopereira Please check again.

2020-08-20 09:12 UTC, ricardopereira commented
I'll accept this for now but maybe it should have a more dedicated method for tag customization. Something like `appearance` for `TagView`'s.

2020-08-20 09:14 UTC, ricardopereira commented
@mobilestar1 Actually, there's already a method for the same purpose 😅
https://github.com/whitesmith/WSTagsField/blob/6553752451d13642c42f470486e89776ddccbf83/Source/WSTagsField.swift#L90-L94

2020-08-20 09:17 UTC, mobilestar1 commented
> @mobilestar1 Actually, there's already a method for the same purpose 😅
> https://github.com/whitesmith/WSTagsField/blob/6553752451d13642c42f470486e89776ddccbf83/Source/WSTagsField.swift#L90-L94
> 
> Sorry, I should've checked this earlier.

Of course, I knew that. As You can see from PR title I added `setCornerRadius` function to avoid `Ambiguous use of 'cornerRadius'` issue.
Several libraries declared cornerRadius variable publicly so it conflicts each other.

2020-08-20 14:51 UTC, ricardopereira commented
@mobilestar1 Ok, could you please share an example project for further investigation? This situation can happen with any property. For example with the `text` property: if someone adds an extension with `UIView.text` then it should not clash with `wsTextField.text`, right? We don't need to create a `setText` just to avoid that particular clash. That would be impractical.

2020-08-20 17:08 UTC, mobilestar1 commented
For example, in my project I added this UIView extension to set corner radius easily.(I checked many other libraries and they also provide this solution)

```
extension UIView {

    @IBInspectable
    var cornerRadius: CGFloat {
        get {
            return layer.cornerRadius
        }
        set {
            layer.cornerRadius = newValue
        }
    }
}
```

Now if I want to set tag field corner radius by tagField.cornerRadius=x, then I got `Ambigious use of cornerRadius` issue.

2020-09-02 07:31 UTC, mobilestar1 commented
any updates?

2020-09-02 08:51 UTC, ricardopereira commented
I think it would make more sense to rename the `cornerRadius` property to `tagsCornerRadius`. It would solve the issue but doing that the `borderWidth`, `borderColor`, etc. need to be renamed too (`tagsBorderWidth`, `tagsBorderColor`...), to keeps things consistent. But the best would be some sort of tags configuration mechanism.

Even so, I'll merge this but keep in mind that it will break in the future. Thanks

2020-09-02 08:52 UTC, merged

2022-03-25 09:29 UTC, aashishSapkotaKC commented
> I think it would make more sense to rename the `cornerRadius` property to `tagsCornerRadius`. It would solve the issue but doing that the `borderWidth`, `borderColor`, etc. need to be renamed too (`tagsBorderWidth`, `tagsBorderColor`...), to keeps things consistent. But the best would be some sort of tags configuration mechanism.
> 
> Even so, I'll merge this but keep in mind that it will break in the future. Thanks

Yes Please do change the borderColor property name likewise, I'm facing the ambiguous issue in borderColor.